//
// Created by carolsand on 2/23/20.
//

#ifndef WEEK6CAROLSANDERSP1STACK_P1STACKTEST_H
#define WEEK6CAROLSANDERSP1STACK_P1STACKTEST_H

#endif //WEEK6CAROLSANDERSP1STACK_P1STACKTEST_H


int main ()
